name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2.0'

    - name: Build
      run: |
        
        xcodebuild  -destination 'generic/platform=iOS' -derivedDataPath "./build/DerivedData"  -configuration Debug   -project MyWebViewApp.xcodeproj -scheme webserver  CODE_SIGNING_ALLOWED=No ONLY_ACTIVE_ARCH=No
    - name: Upload 
      uses: actions/upload-artifact@v3.1.0
      with:
          name: App
          path: /Users/runner/work/CarTube/CarTube/build/DerivedData/Build/Products/Debug-iphoneos/MyWebViewApp.app
          
